-- Hakk Academy schema for PostgreSQL. Generated from schema.sql: identity columns,
-- tsvector search instead of FTS5, tables ordered by dependency.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student','teacher','curator','admin')),
  active INTEGER NOT NULL DEFAULT 1,
  locale TEXT NOT NULL DEFAULT 'kk',
  bio TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS')),
  last_login_at TEXT
);

CREATE TABLE IF NOT EXISTS password_resets (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  teacher_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  curator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS group_members (
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS sources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  book TEXT,
  url TEXT,
  note TEXT
);

CREATE TABLE IF NOT EXISTS courses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  description TEXT,
  direction TEXT NOT NULL DEFAULT 'quran' CHECK (direction IN ('quran','tajweed','arabic','tafsir','hifz')),
  level TEXT,
  color TEXT DEFAULT '#6D4AFF',
  sequential INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'draft',
  sort INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS course_access (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
  granted_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS modules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  sort INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS lessons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id INTEGER NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  goal TEXT,
  youtube_url TEXT,
  duration_min INTEGER DEFAULT 10,
  key_concept TEXT,
  remember TEXT,
  example TEXT,
  example_ar TEXT,
  common_mistake TEXT,
  body TEXT,
  rule_tag TEXT,
  sort INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','review','approved','published')),
  source_id INTEGER REFERENCES sources(id) ON DELETE SET NULL,
  scholar TEXT, book TEXT,
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TEXT,
  is_demo INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS kb_topics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL,         
  section TEXT,                   
  title TEXT NOT NULL,
  summary TEXT,
  simple TEXT,
  rule TEXT,
  examples TEXT,                  
  arabic TEXT,
  audio_url TEXT,
  youtube_url TEXT,
  mistakes TEXT,
  lesson_id INTEGER REFERENCES lessons(id) ON DELETE SET NULL,
  rule_tag TEXT,
  sort INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','review','approved','published')),
  source_id INTEGER REFERENCES sources(id) ON DELETE SET NULL,
  scholar TEXT, book TEXT,
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TEXT,
  is_demo INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS exercises (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id INTEGER REFERENCES lessons(id) ON DELETE CASCADE,
  topic_id INTEGER REFERENCES kb_topics(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('read_aloud','text','single','tf','match','fill','upload')),
  prompt TEXT NOT NULL,
  arabic TEXT,          
  data TEXT,            
  explanation TEXT,
  sort INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS surahs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         
  name_kk TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  name_meaning TEXT,
  ayah_count INTEGER NOT NULL,
  revelation TEXT CHECK (revelation IN ('mecca','medina')),
  description TEXT,
  audio_url TEXT,
  youtube_url TEXT,
  duration_min INTEGER,
  teacher_name TEXT,
  takeaways TEXT,                 
  reflection TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','review','approved','published')),
  source_id INTEGER REFERENCES sources(id) ON DELETE SET NULL,
  scholar TEXT, book TEXT,
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TEXT,
  is_demo INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS tests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  lesson_id INTEGER REFERENCES lessons(id) ON DELETE SET NULL,
  surah_id INTEGER REFERENCES surahs(id) ON DELETE SET NULL,
  topic_id INTEGER REFERENCES kb_topics(id) ON DELETE SET NULL,
  category TEXT DEFAULT 'tajweed',
  pass_score INTEGER NOT NULL DEFAULT 70,
  status TEXT NOT NULL DEFAULT 'published',
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('single','multi','tf','match','fill','arabic_reading','audio_rule')),
  prompt TEXT NOT NULL,
  arabic TEXT,
  audio_url TEXT,
  options TEXT,   
  answer TEXT,    
  explanation TEXT,
  rule_tag TEXT,
  sort INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS test_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  test_id INTEGER NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
  score INTEGER NOT NULL,
  correct INTEGER NOT NULL,
  total INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS answers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id INTEGER NOT NULL REFERENCES test_attempts(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  given TEXT,
  correct INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id INTEGER REFERENCES lessons(id) ON DELETE CASCADE,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  kind TEXT NOT NULL DEFAULT 'text' CHECK (kind IN ('text','upload','audio')),
  due_at TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assignment_id INTEGER REFERENCES assignments(id) ON DELETE CASCADE,
  exercise_id INTEGER REFERENCES exercises(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('text','upload','audio')),
  text TEXT,
  file_path TEXT,
  file_name TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','reread','fix')),
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS teacher_feedback (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id INTEGER NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  teacher_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL,
  comment TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS mistakes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  submission_id INTEGER REFERENCES submissions(id) ON DELETE CASCADE,
  rule_tag TEXT NOT NULL,
  note TEXT,
  resolved INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS student_progress (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress','completed')),
  started_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS')),
  completed_at TEXT,
  PRIMARY KEY (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS ayahs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  surah_id INTEGER NOT NULL REFERENCES surahs(id) ON DELETE CASCADE,
  number INTEGER NOT NULL,
  arabic TEXT NOT NULL,
  global_number INTEGER,
  translation_source TEXT,
  translation TEXT,
  explanation TEXT,
  key_meaning TEXT,
  UNIQUE (surah_id, number)
);

CREATE TABLE IF NOT EXISTS words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arabic TEXT NOT NULL,
  translit TEXT,
  meaning TEXT NOT NULL,
  level TEXT DEFAULT 'beginner',
  topic TEXT,
  audio_url TEXT,
  example_ar TEXT,
  example_kk TEXT,
  in_quran INTEGER NOT NULL DEFAULT 0,
  quran_ref TEXT
);

CREATE TABLE IF NOT EXISTS materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  kind TEXT NOT NULL DEFAULT 'pdf' CHECK (kind IN ('pdf','audio','video','link','recording')),
  category TEXT,
  url TEXT,
  file_path TEXT,
  course_id INTEGER REFERENCES courses(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'published',
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'regular' CHECK (kind IN ('regular','live','offline','exam','event')),
  weekday INTEGER,               
  time TEXT,                     
  starts_at TEXT,                
  duration_min INTEGER NOT NULL DEFAULT 60,
  teacher_name TEXT,
  format TEXT NOT NULL DEFAULT 'online' CHECK (format IN ('online','offline')),
  link TEXT,
  location TEXT,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
  is_live INTEGER NOT NULL DEFAULT 0,
  recording_url TEXT
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT,
  link TEXT,
  kind TEXT DEFAULT 'info',
  read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS bookmarks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL,       
  item_id INTEGER NOT NULL,
  title TEXT,
  subtitle TEXT,
  link TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (user_id, item_type, item_id)
);

CREATE TABLE IF NOT EXISTS certificates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  percent INTEGER NOT NULL,
  completed_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS')),
  downloadable INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS qa_threads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  text TEXT NOT NULL,
  file_path TEXT,
  file_name TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','answered','closed')),
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS qa_replies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id INTEGER NOT NULL REFERENCES qa_threads(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS activity (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,            
  ref_id INTEGER,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS memorization (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  surah_id INTEGER NOT NULL REFERENCES surahs(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('learning','memorized')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (user_id, surah_id)
);

CREATE TABLE IF NOT EXISTS files (
  id TEXT PRIMARY KEY,
  bucket TEXT NOT NULL,
  name TEXT,
  mime TEXT,
  size INTEGER,
  data BYTEA NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS search_index (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT, ref_id INTEGER, link TEXT, scope INTEGER, subtitle TEXT, title TEXT, body TEXT,
  doc tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(title,'')), 'A') ||
    setweight(to_tsvector('simple', coalesce(body,'')), 'B')
  ) STORED
);

CREATE INDEX IF NOT EXISTS idx_lessons_module ON lessons(module_id, sort);

CREATE INDEX IF NOT EXISTS idx_modules_course ON modules(course_id, sort);

CREATE INDEX IF NOT EXISTS idx_progress_user ON student_progress(user_id);

CREATE INDEX IF NOT EXISTS idx_activity_user ON activity(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_activity_kind ON activity(kind, created_at);

CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id, read);

CREATE INDEX IF NOT EXISTS idx_sub_status ON submissions(status);

CREATE INDEX IF NOT EXISTS idx_answers_q ON answers(question_id, correct);

CREATE INDEX IF NOT EXISTS idx_access_course ON course_access(course_id);

CREATE INDEX IF NOT EXISTS idx_mistakes_user ON mistakes(user_id, rule_tag);
CREATE INDEX IF NOT EXISTS idx_search_doc ON search_index USING GIN (doc);
